apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app.name }}
    version: {{ .Values.app.version }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80

